### ISSUE TITLE
Class names need to be modified, In java programs file names and class names are different. 

### ISSUE THREAD

**Issue by yjoshi** [aditya109/git-osp-for-beginners#271] opened 2020-10-24 11:30 UTC
For example in 

- In TemperatureConversion  Folder: celciusToFarenheit file,class name was temperature!

- In CheckPrime folder file name is checkPrime but class name is CheckPrime,

- In PalindromeOrNot file class name is Palindrome!

many more....

- Naming convention needs to be followed.

**Comment by yjoshi** [comment] 2020-10-24 11:49
I have Resolved this in the recent PR #273

**Comment by aditya109** [comment] 2020-10-25 13:02
Hi @yjoshi ! Thanks for opening this issue. Since the issue is resolved by your PR, I'd close close it for now. Happy Hacking!

**Closed by aditya109** 2020-10-25 13:02 UTC
Labels: bug, refactor
